<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-8PV5AO7" ignored="1" name="Leads" tests="2" failures="1" timestamp="21 Jul 2018 07:45:39 GMT" time="0.031" errors="0">
  <testcase name="createLead" time="0.016" classname="testCase.CreateLead">
    <failure type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
at wdMethods.SeMethods.click(SeMethods.java:136)
at testCase.CreateLead.createLead(CreateLead.java:15)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- createLead -->
  <testcase name="LeadMerge" time="0.0" classname="testCase.MergeLead">
    <skipped/>
  </testcase> <!-- LeadMerge -->
  <testcase name="Duplicate" time="0.0" classname="testCase.DuplicateLead">
    <ignored/>
  </testcase> <!-- Duplicate -->
</testsuite> <!-- Leads -->
